# Generated by Django 5.2.7 on 2026-04-27 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDQPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinformation',
            name='process_benefits',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='processinformation',
            name='process_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processinformation',
            name='process_issue',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='processinformation',
            name='process_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='processinformation',
            name='process_solution',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='processinformation',
            name='process_start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='processinformation',
            name='process_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
